matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8.3
language: generic
script:
  - swift build
  - swift test
notifications:
    email:
      on_success: never
      on_failure: change
