matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      cache:
          directories:
                - ${PWD}/swift-3.1-RELEASE-ubuntu14.04
      before_install:
        - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
        - wget https://swift.org/builds/swift-3.1-release/ubuntu1404/swift-3.1-RELEASE/swift-3.1-RELEASE-ubuntu14.04.tar.gz
        - tar xzf swift-3.1-RELEASE-ubuntu14.04.tar.gz
        - export PATH=${PWD}/swift-3.1-RELEASE-ubuntu14.04/usr/bin:"${PATH}"
      script:
        - git clone https://github.com/apple/swift-package-manager
        - cd swift-package-manager && git checkout 58f859a && cd ../
        - swift-package-manager/Utilities/bootstrap
        - ${PWD}/.build/debug/swift-build
        - ${PWD}/.build/debug/swift-test
    - os: osx
      osx_image: xcode8.3
      script:
        - swift build
        - swift test
language: generic
notifications:
    email:
      on_success: never
      on_failure: change
